/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project113;

/**
 *
 * @author raneemalrashoud
 */
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
//import java.awt.Image;
import java.io.*;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
//import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
public class RentCarsFrame extends javax.swing.JFrame {

  private final CarRental frame;
    ButtonGroup button=new ButtonGroup();
   
   
    public RentCarsFrame() {
       
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        ImageIcon img = new ImageIcon(new ImageIcon("src/project113/images copy 2.jpeg").getImage().getScaledInstance(200, 70, Image.SCALE_SMOOTH));
        jButton1.setIcon(img);
       jButton1.setHorizontalTextPosition(jButton1.CENTER);
       returnCarButton3.setIcon(img);
       returnCarButton3.setHorizontalTextPosition(jButton1.CENTER);
      rentButton2.setIcon(img);
       rentButton2.setHorizontalTextPosition(jButton1.CENTER);
        
          button.add(economyB);
        button.add(VIPB);
          frame = new CarRental(100);
        readData();

        onExitListener();
    }
    
     public final boolean readData() {

        try {
            frame.loadFromFile();
            return true;

        } catch (IOException ex) {

            JOptionPane.showMessageDialog(this, "something went wrong while reading the data\n" + ex, "Rental car System", JOptionPane.ERROR_MESSAGE);

        } catch (ClassNotFoundException ex) {

            JOptionPane.showMessageDialog(this, "something went wrong while reading the data\n" + ex, "Rental car System", JOptionPane.ERROR_MESSAGE);

        }
        return false;

    }
     
     
     public final void onExitListener() {
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                int answer = JOptionPane.showConfirmDialog(null, "SAVE CHANGES?", "Attention!!!", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);

                if (answer == JOptionPane.YES_OPTION) {

                    try {

                  frame.saveToFile();

                        JOptionPane.showMessageDialog(null, "Thank you for using our app \nAll changes have been saved", "See you soon :)",
                                JOptionPane.INFORMATION_MESSAGE);

                    } catch (FileNotFoundException ex) {
                        JOptionPane.showMessageDialog(null, "something went wrong while reading the data", "Rental car System", JOptionPane.ERROR_MESSAGE);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(null, "something went wrong while reading the data", "Rental car System", JOptionPane.ERROR_MESSAGE);
                    }

                } else {

                    JOptionPane.showMessageDialog(null, "Thank you for using our app \nAll changes haven't been saved", "See you soon :)",
                            JOptionPane.INFORMATION_MESSAGE);
                }
                System.exit(0);

            }
        }
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addNewCarPanel1 = new javax.swing.JPanel();
        PlateNoLabel1 = new javax.swing.JLabel();
        PriceLabel2 = new javax.swing.JLabel();
        modelLabel3 = new javax.swing.JLabel();
        colorLabel4 = new javax.swing.JLabel();
        economyB = new javax.swing.JRadioButton();
        VIPB = new javax.swing.JRadioButton();
        driverPanel = new javax.swing.JPanel();
        idInDriverPanel = new javax.swing.JLabel();
        nameInDriverPanel = new javax.swing.JLabel();
        ansName = new javax.swing.JTextField();
        ansID = new javax.swing.JTextField();
        plateNoTextField1 = new javax.swing.JTextField();
        priceTextField2 = new javax.swing.JTextField();
        colorTextField3 = new javax.swing.JTextField();
        ModelTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        rentCarPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rentOfPlateNoTextField1 = new javax.swing.JTextField();
        cusInfoPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cusPhoneTextField2 = new javax.swing.JTextField();
        cusNameTextField3 = new javax.swing.JTextField();
        cusIDTextField4 = new javax.swing.JTextField();
        noOfDaysRentTextField5 = new javax.swing.JTextField();
        rentButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaOfInfo = new javax.swing.JTextArea();
        showEconomyButton2 = new javax.swing.JButton();
        showVIPbutton3 = new javax.swing.JButton();
        returnCarPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        plateNoReturnCarTextField6 = new javax.swing.JTextField();
        returnCarButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rental car system ");
        setMinimumSize(new java.awt.Dimension(1100, 850));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addNewCarPanel1.setBackground(new java.awt.Color(255, 255, 255));
        addNewCarPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add New Car", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("PT Mono", 1, 13), new java.awt.Color(51, 51, 51))); // NOI18N
        addNewCarPanel1.setForeground(new java.awt.Color(153, 153, 153));
        addNewCarPanel1.setToolTipText("");
        addNewCarPanel1.setMaximumSize(new java.awt.Dimension(1100, 890));

        PlateNoLabel1.setFont(new java.awt.Font("Noteworthy", 1, 13)); // NOI18N
        PlateNoLabel1.setText("Plate No. :");

        PriceLabel2.setFont(new java.awt.Font("Noteworthy", 1, 13)); // NOI18N
        PriceLabel2.setText("Price per day :");

        modelLabel3.setFont(new java.awt.Font("Noteworthy", 1, 13)); // NOI18N
        modelLabel3.setText("Model :");

        colorLabel4.setFont(new java.awt.Font("Noteworthy", 1, 13)); // NOI18N
        colorLabel4.setText("Color:");

        economyB.setFont(new java.awt.Font("Noteworthy", 1, 13)); // NOI18N
        economyB.setSelected(true);
        economyB.setText("Economy");
        economyB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                economyBActionPerformed(evt);
            }
        });

        VIPB.setFont(new java.awt.Font("Noteworthy", 1, 13)); // NOI18N
        VIPB.setText("VIP");
        VIPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIPBActionPerformed(evt);
            }
        });

        driverPanel.setBackground(new java.awt.Color(255, 255, 255));
        driverPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Driver"));
        driverPanel.setForeground(new java.awt.Color(255, 255, 255));
        driverPanel.setEnabled(false);

        idInDriverPanel.setText("ID :");
        idInDriverPanel.setEnabled(false);

        nameInDriverPanel.setText("Name :");
        nameInDriverPanel.setEnabled(false);

        ansID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout driverPanelLayout = new javax.swing.GroupLayout(driverPanel);
        driverPanel.setLayout(driverPanelLayout);
        driverPanelLayout.setHorizontalGroup(
            driverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(driverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameInDriverPanel)
                    .addComponent(idInDriverPanel))
                .addGap(18, 18, 18)
                .addGroup(driverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ansID, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ansName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        driverPanelLayout.setVerticalGroup(
            driverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverPanelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(driverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idInDriverPanel)
                    .addComponent(ansID, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(driverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameInDriverPanel)
                    .addComponent(ansName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        plateNoTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        plateNoTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plateNoTextField1ActionPerformed(evt);
            }
        });

        priceTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        priceTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextField2ActionPerformed(evt);
            }
        });

        colorTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorTextField3ActionPerformed(evt);
            }
        });

        ModelTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(235, 235, 235));
        jButton1.setFont(new java.awt.Font("Phosphate", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add New Car");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addNewCarPanel1Layout = new javax.swing.GroupLayout(addNewCarPanel1);
        addNewCarPanel1.setLayout(addNewCarPanel1Layout);
        addNewCarPanel1Layout.setHorizontalGroup(
            addNewCarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewCarPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addNewCarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addNewCarPanel1Layout.createSequentialGroup()
                        .addGroup(addNewCarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PlateNoLabel1)
                            .addComponent(PriceLabel2)
                            .addGroup(addNewCarPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(addNewCarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(colorLabel4)
                                    .addComponent(modelLabel3))))
                        .addGap(18, 18, 18)
                        .addGroup(addNewCarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addNewCarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ModelTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                .addComponent(colorTextField3)
                                .addComponent(priceTextField2))
                            .addComponent(plateNoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addNewCarPanel1Layout.createSequentialGroup()
                        .addGroup(addNewCarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(economyB)
                            .addComponent(VIPB))
                        .addGap(18, 18, 18)
                        .addComponent(driverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewCarPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        addNewCarPanel1Layout.setVerticalGroup(
            addNewCarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewCarPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(addNewCarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlateNoLabel1)
                    .addComponent(plateNoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addNewCarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(PriceLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addNewCarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addNewCarPanel1Layout.createSequentialGroup()
                        .addComponent(modelLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ModelTextField4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addNewCarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorLabel4)
                    .addComponent(colorTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(addNewCarPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addNewCarPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(economyB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(VIPB))
                    .addGroup(addNewCarPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(driverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );

        getContentPane().add(addNewCarPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 428, 460));

        rentCarPanel2.setBackground(new java.awt.Color(255, 255, 255));
        rentCarPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rent Car", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("PT Mono", 1, 18))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Noteworthy", 1, 13)); // NOI18N
        jLabel3.setText("PlateNo :");

        jLabel5.setFont(new java.awt.Font("Noteworthy", 1, 13)); // NOI18N
        jLabel5.setText("NO. of days :");

        rentOfPlateNoTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cusInfoPanel1.setBackground(new java.awt.Color(255, 255, 255));
        cusInfoPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Menlo", 1, 18), new java.awt.Color(102, 102, 102))); // NOI18N
        cusInfoPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Noteworthy", 1, 18)); // NOI18N
        jLabel6.setText("ID : ");
        cusInfoPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 38, -1, -1));

        jLabel7.setFont(new java.awt.Font("Noteworthy", 1, 14)); // NOI18N
        jLabel7.setText("Name :");
        cusInfoPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 77, -1, -1));

        jLabel8.setFont(new java.awt.Font("Noteworthy", 1, 14)); // NOI18N
        jLabel8.setText("Phone :");
        cusInfoPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        cusPhoneTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cusPhoneTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusPhoneTextField2ActionPerformed(evt);
            }
        });
        cusInfoPanel1.add(cusPhoneTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 150, 30));

        cusNameTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cusInfoPanel1.add(cusNameTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 73, 150, 30));

        cusIDTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cusInfoPanel1.add(cusIDTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 30, 150, 30));

        rentButton2.setFont(new java.awt.Font("Phosphate", 1, 24)); // NOI18N
        rentButton2.setForeground(new java.awt.Color(255, 255, 255));
        rentButton2.setText("Rent");
        rentButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rentButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rentCarPanel2Layout = new javax.swing.GroupLayout(rentCarPanel2);
        rentCarPanel2.setLayout(rentCarPanel2Layout);
        rentCarPanel2Layout.setHorizontalGroup(
            rentCarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentCarPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(rentCarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cusInfoPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                    .addGroup(rentCarPanel2Layout.createSequentialGroup()
                        .addGroup(rentCarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(48, 48, 48)
                        .addGroup(rentCarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(noOfDaysRentTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(rentOfPlateNoTextField1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(rentCarPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(rentButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rentCarPanel2Layout.setVerticalGroup(
            rentCarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentCarPanel2Layout.createSequentialGroup()
                .addGroup(rentCarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rentCarPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3))
                    .addGroup(rentCarPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(rentOfPlateNoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rentCarPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(noOfDaysRentTextField5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cusInfoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rentButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        getContentPane().add(rentCarPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 490, 330));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Show Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("PT Mono", 1, 18), new java.awt.Color(51, 51, 51))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(153, 153, 153));
        jPanel3.setToolTipText("");

        areaOfInfo.setEditable(false);
        areaOfInfo.setColumns(20);
        areaOfInfo.setRows(5);
        jScrollPane1.setViewportView(areaOfInfo);

        showEconomyButton2.setFont(new java.awt.Font("Noteworthy", 1, 13)); // NOI18N
        showEconomyButton2.setText("Show all available Economy");
        showEconomyButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showEconomyButton2ActionPerformed(evt);
            }
        });

        showVIPbutton3.setFont(new java.awt.Font("Noteworthy", 1, 13)); // NOI18N
        showVIPbutton3.setText("Show all available VIP");
        showVIPbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showVIPbutton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(showEconomyButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(showVIPbutton3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showEconomyButton2)
                    .addComponent(showVIPbutton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 450, 240));

        returnCarPanel4.setBackground(new java.awt.Color(255, 255, 255));
        returnCarPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Return Car", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monospaced", 1, 18), new java.awt.Color(51, 51, 51))); // NOI18N
        returnCarPanel4.setForeground(new java.awt.Color(153, 153, 153));
        returnCarPanel4.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Noteworthy", 1, 13)); // NOI18N
        jLabel9.setText("PlateNo :");

        plateNoReturnCarTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        plateNoReturnCarTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plateNoReturnCarTextField6ActionPerformed(evt);
            }
        });

        returnCarButton3.setFont(new java.awt.Font("Phosphate", 1, 24)); // NOI18N
        returnCarButton3.setForeground(new java.awt.Color(255, 255, 255));
        returnCarButton3.setText("Return car");
        returnCarButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnCarButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout returnCarPanel4Layout = new javax.swing.GroupLayout(returnCarPanel4);
        returnCarPanel4.setLayout(returnCarPanel4Layout);
        returnCarPanel4Layout.setHorizontalGroup(
            returnCarPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnCarPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(35, 35, 35)
                .addGroup(returnCarPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(returnCarButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plateNoReturnCarTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        returnCarPanel4Layout.setVerticalGroup(
            returnCarPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnCarPanel4Layout.createSequentialGroup()
                .addGroup(returnCarPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnCarPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addComponent(plateNoReturnCarTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnCarButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(returnCarPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 650, 490, 140));

        jLabel1.setBackground(new java.awt.Color(128, 115, 67));
        jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Rental Cars System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project113/images.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 480, 150));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project113/download.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project113/images copy.jpeg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 229, 233));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void economyBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_economyBActionPerformed
          idInDriverPanel.setEnabled(false);
        nameInDriverPanel.setEnabled(false);
        ansID.setEnabled(false);
        ansName.setEnabled(false);
        driverPanel.setEnabled(false);
    }//GEN-LAST:event_economyBActionPerformed

    private void VIPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIPBActionPerformed
        idInDriverPanel.setEnabled(true);
        nameInDriverPanel.setEnabled(true);
        ansID.setEnabled(true);
        ansName.setEnabled(true);
        driverPanel.setEnabled(true);
        
    }//GEN-LAST:event_VIPBActionPerformed

    private boolean isEmpty(JTextField field, String field2) {

        if (field.getText().trim().equals("")) {
            // error msg
            JOptionPane.showMessageDialog(this, field2 + " This field is required", "Error",JOptionPane.ERROR_MESSAGE);
            field.requestFocus();
            return false;
        }

        return true;

    }
    private void ansIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansIDActionPerformed

    private void plateNoTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plateNoTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plateNoTextField1ActionPerformed

    private void priceTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextField2ActionPerformed

    private void colorTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        String plateNo, model, color,since="",type=""; double pricePerDay; boolean isDone;
        

        //check if the fields are empty or not       
        if (!isEmpty(plateNoTextField1, "Plate No.")) {
            return;
        }

        plateNo = plateNoTextField1.getText().trim();

        if (!isEmpty(priceTextField2, "Price Per Day")) {
            return;
        }

        if (!checkNum(priceTextField2, "Price Per Day")) {
            return;

        }
        pricePerDay = getParsingValue(priceTextField2);

        if (!isTrueValue(pricePerDay, "Price Per Day", 0)) {
            return;

        }

        if (!isEmpty(ModelTextField4, "Model")) {
            return;
        }
        model = ModelTextField4.getText().trim();

        if (!isEmpty(colorTextField3, "Color")) {
            return;
        }

        color = colorTextField3.getText().trim();
        
        
        

        if (VIPB.isSelected()) {//VIP car
            if (!isEmpty(ansID, "Driver Id")) {
                return;
            }

            if (!checkNum(ansID, "Driver Id")) {
                return;

            }

            if (!isEmpty(ansName, "Driver Name")) {
                return;
            }

            int driverId = (int) getParsingValue(ansID);

            String driverName = ansName.getText().trim();

            isDone = frame.addCar(new VIP(plateNo, pricePerDay, model, color, new Driver(driverId, driverName)));
            type="VIP";
        } else {
//for economy car

            isDone = frame.addCar(new Economy(plateNo, pricePerDay, model, color));
            type="Economy";

        }

        if (isDone) {
            JOptionPane.showMessageDialog(this, type+" car which is entered currentally car has been added successfully :)", "New Car",
                    JOptionPane.INFORMATION_MESSAGE);
            //reset fields
            clearAllTextFieldsOfPanel(addNewCarPanel1);
            clearAllTextFieldsOfPanel(driverPanel);

        } else {
            since="That car already in the compound:(";
            Car[] cars=frame.getCarlist();
            if(cars.length==100)
since="already it's added :(";
            JOptionPane.showMessageDialog(this, "Sorry can't add that car since "+since, "Error",
                    JOptionPane.ERROR_MESSAGE);
        }


    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void showEconomyButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showEconomyButton2ActionPerformed
                                                     

        areaOfInfo.setText("");//To be sure it is empty space 
        Economy[] cars = frame.searchAvailableEconomy();
        if (cars == null) {
            areaOfInfo.append("\nCars of Economy type aren't available!");
            //////checkkk it 

        } else {
            for (Economy car : cars) {
                areaOfInfo.append("\n" + car.toString());

            
        }

    } 
    }//GEN-LAST:event_showEconomyButton2ActionPerformed

    private void showVIPbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showVIPbutton3ActionPerformed
        areaOfInfo.setText("");
        VIP[] cars = frame.searchAvailableVIP();
        if (cars == null) {
            areaOfInfo.append("\nCars of VIP type aren't available!");
        

        } else {
            for (VIP car : cars) 
                areaOfInfo.append("\n" + car.toString());//to show that all we have
               
            
        }
    }//GEN-LAST:event_showVIPbutton3ActionPerformed

    private void rentButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentButton2ActionPerformed
      
        String plateNo, cusName; int nOdays, cusID; long phoneNum;
               
        if (!isEmpty(rentOfPlateNoTextField1, "Plate No")) {
            return;
        }

        plateNo = rentOfPlateNoTextField1.getText().trim();

        if (!isEmpty(noOfDaysRentTextField5, "Days")) {
            return;
        }

        if (!checkNum(noOfDaysRentTextField5, "Days")) {
            return;

        }
        nOdays = (int) getParsingValue(noOfDaysRentTextField5);

        if (!isTrueValue(nOdays, "days", 1)) {
            return;

        }

        if (!isEmpty(cusIDTextField4, "Customer ID")) {
            return;
        }

        if (!checkNum(cusIDTextField4, "Customer ID")) {
            return;

        }
        cusID = (int) getParsingValue(cusIDTextField4);

        if (!isEmpty(cusNameTextField3, "Customer Name")) {
            return;
        }
        cusName = cusNameTextField3.getText().trim();

        if (!isEmpty(cusPhoneTextField2, "Phone")) {
            return;
        }

        if (!checkNum(cusPhoneTextField2, "Phone"))
        {
            return;

        }
        phoneNum = (long) getParsingValue(cusPhoneTextField2);

        Customer customer = new Customer(cusID, cusName, phoneNum);
        String info = frame.rentCar(plateNo, customer, nOdays);

        if (info == null) {

            JOptionPane.showMessageDialog(this, "Sorry, can't rent that car \n plate number is invalid number\nor the car isn't available", "Error",
                    JOptionPane.ERROR_MESSAGE);

        } else {

            JOptionPane.showMessageDialog(this, info, "Rent Car",
                    JOptionPane.INFORMATION_MESSAGE);
            //reset fields
            clearAllTextFieldsOfPanel(rentCarPanel2);
            clearAllTextFieldsOfPanel(cusInfoPanel1);

            try {
                //concat the customer info to the bill to save 'em
                info += ("\n") + customer;
                billInFile(cusName + "_" + cusID + ".txt", info);
            } catch (FileNotFoundException ex) {

                JOptionPane.showMessageDialog(this, ex.toString(), "Error",
                        JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_rentButton2ActionPerformed

   public void billInFile(String fileName, String info) throws FileNotFoundException {

        
       File f= new File(fileName);
        PrintWriter pw = new PrintWriter(new FileOutputStream(f));
        pw.println(info);
       //since it's text file
        pw.close();

    }
    private void returnCarButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnCarButton3ActionPerformed
                                                   

        String plateNo;
               
        if (!isEmpty(plateNoReturnCarTextField6, "Plate No.")) {
            return;
        }
        plateNo = plateNoReturnCarTextField6.getText().trim();

        if (frame.returnCar(plateNo)) {
            JOptionPane.showMessageDialog(this, "Car has been returned :)\nSee you soon", "Return Car",
                    JOptionPane.INFORMATION_MESSAGE);
            //reset fields
            clearAllTextFieldsOfPanel(returnCarPanel4);
        } else {

            JOptionPane.showMessageDialog(this, "Sorry,can't return that car\nPlate number is invalid\nOr that car has returned", "Error",
                    JOptionPane.ERROR_MESSAGE);

        }


   
    }//GEN-LAST:event_returnCarButton3ActionPerformed

    private void plateNoReturnCarTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plateNoReturnCarTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plateNoReturnCarTextField6ActionPerformed

    private void cusPhoneTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusPhoneTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusPhoneTextField2ActionPerformed
private boolean isTrueValue(double num, String field, int minimum) {

        if (num < minimum) {
           
            JOptionPane.showMessageDialog(this, "The vlaue of " + field + " should't be less than " + minimum, "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;

    }
    public void clearAllTextFieldsOfPanel(JPanel panel) {
//!!!!!!! be sure if the size untill the length or not
         Component[] components = panel.getComponents();
        for (Component component : components) {
            if (component instanceof JTextField) {
                ((JTextField) component).setText("");
            }
        }//to clear the field
            }
        
    
    private boolean checkNum(JTextField field, String field2) {
        String newField = field.getText().trim();
        field.requestFocus();
        try {
            Double.parseDouble(newField);
// will throw an exception if it's not a numerical value
            return true; 
// it's a numerical value :)
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "You hava to enter a numerical value !! " + field2 + " Field.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
   
    private double getParsingValue(JTextField field) {
        field.requestFocus();
       
             double str=  Double.parseDouble(field.getText().trim());
                return str;
    }
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("MAC".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentCarsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentCarsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentCarsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentCarsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentCarsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ModelTextField4;
    private javax.swing.JLabel PlateNoLabel1;
    private javax.swing.JLabel PriceLabel2;
    private javax.swing.JRadioButton VIPB;
    private javax.swing.JPanel addNewCarPanel1;
    private javax.swing.JTextField ansID;
    private javax.swing.JTextField ansName;
    private javax.swing.JTextArea areaOfInfo;
    private javax.swing.JLabel colorLabel4;
    private javax.swing.JTextField colorTextField3;
    private javax.swing.JTextField cusIDTextField4;
    private javax.swing.JPanel cusInfoPanel1;
    private javax.swing.JTextField cusNameTextField3;
    private javax.swing.JTextField cusPhoneTextField2;
    private javax.swing.JPanel driverPanel;
    private javax.swing.JRadioButton economyB;
    private javax.swing.JLabel idInDriverPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel modelLabel3;
    private javax.swing.JLabel nameInDriverPanel;
    private javax.swing.JTextField noOfDaysRentTextField5;
    private javax.swing.JTextField plateNoReturnCarTextField6;
    private javax.swing.JTextField plateNoTextField1;
    private javax.swing.JTextField priceTextField2;
    private javax.swing.JButton rentButton2;
    private javax.swing.JPanel rentCarPanel2;
    private javax.swing.JTextField rentOfPlateNoTextField1;
    private javax.swing.JButton returnCarButton3;
    private javax.swing.JPanel returnCarPanel4;
    private javax.swing.JButton showEconomyButton2;
    private javax.swing.JButton showVIPbutton3;
    // End of variables declaration//GEN-END:variables
}
